# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ManyToManyField(to='details.cl'),
        ),
    ]
