# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_remove_teacher_hw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cl',
            new_name='Class',
        ),
    ]
