# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20180104_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 4, 19, 54, 23, 94000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
